export const protocolCharts = {
	TVL: 'tvl',
	Mcap: 'mcap',
	'Token Price': 'tokenPrice',
	FDV: 'fdv',
	Fees: 'fees',
	Revenue: 'revenue',
	'Holders Revenue': 'holdersRevenue',
	'DEX Volume': 'dexVolume',
	'Perp Volume': 'perpVolume',
	Unlocks: 'unlocks',
	'Active Addresses': 'activeAddresses',
	'New Addresses': 'newAddresses',
	Transactions: 'transactions',
	'Gas Used': 'gasUsed',
	Staking: 'staking',
	Borrowed: 'borrowed',
	'Median APY': 'medianApy',
	'USD Inflows': 'usdInflows',
	'Total Proposals': 'totalProposals',
	'Successful Proposals': 'successfulProposals',
	'Max Votes': 'maxVotes',
	Treasury: 'treasury',
	'Bridge Deposits': 'bridgeDeposits',
	'Bridge Withdrawals': 'bridgeWithdrawals',
	'Token Volume': 'tokenVolume',
	'Token Liquidity': 'tokenLiquidity',
	Tweets: 'tweets',
	Developers: 'developers',
	Contributers: 'contributers',
	'Devs Commits': 'devsCommits',
	'Contributers Commits': 'contributersCommits',
	'NFT Volume': 'nftVolume',
	'Options Premium Volume': 'optionsPremiumVolume',
	'Options Notional Volume': 'optionsNotionalVolume',
	'Perp Aggregator Volume': 'perpAggregatorVolume',
	'Bridge Aggregator Volume': 'bridgeAggregatorVolume',
	'DEX Aggregator Volume': 'dexAggregatorVolume',
	Incentives: 'incentives'
} as const

export type ProtocolChartsLabels = keyof typeof protocolCharts
export const allCharts = Object.keys(protocolCharts) as ProtocolChartsLabels[]
export type ProtocolChartsQueryParams = typeof protocolCharts[keyof typeof protocolCharts]

export const yAxisByChart: {
	[K in keyof typeof protocolCharts]: ProtocolChartsLabels
} = {
	TVL: 'TVL',
	Mcap: 'TVL',
	FDV: 'TVL',
	Borrowed: 'TVL',
	Staking: 'TVL',
	'Token Price': 'Token Price',
	'Token Volume': 'Token Volume',
	'Token Liquidity': 'Token Liquidity',
	'Bridge Deposits': 'Bridge Deposits',
	'Bridge Withdrawals': 'Bridge Deposits',
	Fees: 'Fees',
	Revenue: 'Fees',
	'Holders Revenue': 'Fees',
	Incentives: 'Fees',
	'DEX Volume': 'DEX Volume',
	'Perp Volume': 'DEX Volume',
	'Options Premium Volume': 'DEX Volume',
	'Options Notional Volume': 'DEX Volume',
	'Perp Aggregator Volume': 'DEX Volume',
	'Bridge Aggregator Volume': 'DEX Volume',
	'DEX Aggregator Volume': 'DEX Volume',
	Unlocks: 'Unlocks',
	'Active Addresses': 'Active Addresses',
	'New Addresses': 'Active Addresses',
	Transactions: 'Transactions',
	'Gas Used': 'Gas Used',
	'Median APY': 'Median APY',
	'USD Inflows': 'USD Inflows',
	'Total Proposals': 'Total Proposals',
	'Successful Proposals': 'Total Proposals',
	'Max Votes': 'Max Votes',
	Treasury: 'Treasury',
	Tweets: 'Tweets',
	Developers: 'Developers',
	Contributers: 'Contributers',
	'Devs Commits': 'Devs Commits',
	'Contributers Commits': 'Contributers Commits',
	'NFT Volume': 'NFT Volume'
}

export const BAR_CHARTS: ProtocolChartsLabels[] = [
	'DEX Volume',
	'Perp Volume',
	'Fees',
	'Revenue',
	'Holders Revenue',
	'Incentives',
	'Active Addresses',
	'New Addresses',
	'Transactions',
	'Gas Used',
	'USD Inflows',
	'Total Proposals',
	'Successful Proposals',
	'Max Votes',
	'Bridge Deposits',
	'Bridge Withdrawals',
	'Token Volume',
	'Tweets',
	'Developers',
	'Contributers',
	'Devs Commits',
	'Contributers Commits',
	'NFT Volume',
	'DEX Aggregator Volume',
	'Options Premium Volume',
	'Options Notional Volume',
	'Perp Aggregator Volume',
	'Bridge Aggregator Volume'
]

export const DISABLED_CUMULATIVE_CHARTS: ProtocolChartsLabels[] = [
	'Developers',
	'Contributers',
	'Devs Commits',
	'Contributers Commits'
]
