export const BAR_CHARTS = [
	'DEXs Volume',
	'DEX Volume',
	'Perps Volume',
	'Perp Volume',
	'Fees',
	'Revenue',
	'Holders Revenue',
	'Incentives',
	'Active Addresses',
	'New Addresses',
	'Transactions',
	'Gas Used',
	'USD Inflows',
	'Total Proposals',
	'Successful Proposals',
	'Max Votes',
	'Bridge Deposits',
	'Bridge Withdrawals',
	'Token Volume',
	'Tweets',
	'Developers',
	'Contributors',
	'Devs Commits',
	'Contributors Commits',
	'NFT Volume',
	'DEX Aggregators Volume',
	'DEX Aggregator Volume',
	'Options Premium Volume',
	'Options Notional Volume',
	'Perps Aggregators Volume',
	'Perp Aggregator Volume',
	'Bridge Aggregators Volume',
	'Bridge Aggregator Volume'
]

export const DISABLED_CUMULATIVE_CHARTS = ['Developers', 'Contributors', 'Devs Commits', 'Contributors Commits']
