export const BAR_CHARTS = [
	'DEXs Volume',
	'Volume',
	'Perps Volume',
	'Fees',
	'Revenue',
	'Incentives',
	'Active Addresses',
	'New Addresses',
	'Transactions',
	'Gas Used',
	'USD Inflows',
	'Total Proposals',
	'Successful Proposals',
	'Max Votes',
	'Bridge Deposits',
	'Bridge Withdrawals',
	'Token Volume',
	'Tweets',
	'Developers',
	'Contributers',
	'Devs Commits',
	'Contributers Commits',
	'NFT Volume',
	'Aggregators Volume',
	'Options Premium Volume',
	'Options Notional Volume',
	'Perps Aggregators Volume',
	'Bridge Aggregators Volume'
]

export const DISABLED_CUMULATIVE_CHARTS = ['Developers', 'Contributers', 'Devs Commits', 'Contributers Commits']
