import { feesOptions } from '~/components/Filters/options'
import { AdapterByChain } from '~/containers/DimensionAdapters/AdapterByChain'
import { ADAPTER_TYPES } from '~/containers/DimensionAdapters/constants'
import { getAdapterByChainPageData } from '~/containers/DimensionAdapters/queries'
import type { IAdapterByChainPageData } from '~/containers/DimensionAdapters/types'
import { fetchEntityQuestions } from '~/containers/LlamaAI/api'
import Layout from '~/layout'
import { maxAgeForNext } from '~/utils/maxAgeForNext'
import { withPerformanceLogging } from '~/utils/perf'

const adapterType = ADAPTER_TYPES.FEES
const type = 'Fees'

export const getStaticProps = withPerformanceLogging(`${type}/index`, async () => {
	const data = await getAdapterByChainPageData({
		adapterType,
		chain: 'All',
		route: 'fees',
		metricName: type
	}).catch((e) => console.info(`Chain page data not found ${adapterType} : ALL_CHAINS`, e))

	if (!data) return { notFound: true }

	const feesContext = {
		total24h: data.total24h ?? null,
		total7d: data.total7d ?? null,
		change_1d: data.change_1d ?? null,
		change_7dover7d: data.change_7dover7d ?? null,
		change_1m: data.change_1m ?? null,
		topProtocols: data.protocols.slice(0, 15).map((p) => ({
			name: p.name,
			fees24h: p.total24h ?? null,
			fees7d: p.total7d ?? null,
			mcap: p.mcap ?? null,
			pf: p.pfOrPs ?? null,
			chains: p.chains?.slice(0, 3) ?? null
		}))
	}
	const { questions: entityQuestions } = await fetchEntityQuestions('fees', 'page', feesContext)

	return {
		props: { ...data, entityQuestions },
		revalidate: maxAgeForNext([22])
	}
})

const pageName = ['Protocols', 'ranked by', type]

const FeesOnAllChains = (props: IAdapterByChainPageData) => {
	return (
		<Layout
			title="Protocol Fees Rankings - Fees Generated - DefiLlama"
			description="Track total fees generated by DeFi protocols from users. Compare trading fees, swap fees, and lending fees across Uniswap, Lido, Aave, and 1000+ protocols. Real-time fee generation analytics across all chains."
			canonicalUrl={`/fees`}
			metricFilters={feesOptions}
			metricFiltersLabel="Include in Fees"
			pageName={pageName}
		>
			<AdapterByChain {...props} type={type} />
		</Layout>
	)
}

export default FeesOnAllChains
