// MAKE SURE TO UPDATE ON SERVER TOO https://github.com/DefiLlama/defillama-server/blob/master/defi/src/updateSearch.ts
export const protocolCharts = {
	TVL: 'tvl',
	'Total Assets': 'totalAssets',
	TVS: 'tvs',
	Mcap: 'mcap',
	'Token Price': 'tokenPrice',
	'Token Volume': 'tokenVolume',
	'Token Liquidity': 'tokenLiquidity',
	FDV: 'fdv',
	Fees: 'fees',
	Revenue: 'revenue',
	'Holders Revenue': 'holdersRevenue',
	'DEX Volume': 'dexVolume',
	'Perp Volume': 'perpVolume',
	'Open Interest': 'openInterest',
	'Options Premium Volume': 'optionsPremiumVolume',
	'Options Notional Volume': 'optionsNotionalVolume',
	'Perp Aggregator Volume': 'perpAggregatorVolume',
	'Bridge Aggregator Volume': 'bridgeAggregatorVolume',
	'DEX Aggregator Volume': 'dexAggregatorVolume',
	Unlocks: 'unlocks',
	Incentives: 'incentives',
	Staking: 'staking_tvl',
	Borrowed: 'borrowed_tvl',
	'Median APY': 'medianApy',
	'USD Inflows': 'usdInflows',
	Treasury: 'treasury',
	'Bridge Deposits': 'bridgeDeposits',
	'Bridge Withdrawals': 'bridgeWithdrawals',
	'Total Proposals': 'totalProposals',
	'Successful Proposals': 'successfulProposals',
	'Max Votes': 'maxVotes',
	'Active Addresses': 'activeAddresses',
	'New Addresses': 'newAddresses',
	Transactions: 'transactions',
	'Gas Used': 'gasUsed',
	Tweets: 'tweets',
	'NFT Volume': 'nftVolume',
	'Bridge Volume': 'bridgeVolume'
} as const

export type ProtocolChartsLabels = keyof typeof protocolCharts
export const allCharts = Object.keys(protocolCharts) as ProtocolChartsLabels[]
export type ProtocolChartsQueryParams = (typeof protocolCharts)[keyof typeof protocolCharts]

export const yAxisByChart: {
	[K in keyof typeof protocolCharts]: ProtocolChartsLabels
} = {
	TVL: 'TVL',
	'Total Assets': 'TVL',
	TVS: 'TVL',
	Mcap: 'TVL',
	FDV: 'TVL',
	Borrowed: 'TVL',
	Staking: 'TVL',
	'Token Price': 'Token Price',
	'Token Volume': 'Token Volume',
	'Token Liquidity': 'Token Liquidity',
	'Bridge Deposits': 'Bridge Deposits',
	'Bridge Withdrawals': 'Bridge Deposits',
	Fees: 'Fees',
	Revenue: 'Fees',
	'Holders Revenue': 'Fees',
	Incentives: 'Fees',
	'DEX Volume': 'DEX Volume',
	'Perp Volume': 'DEX Volume',
	'Open Interest': 'Open Interest',
	'Options Premium Volume': 'DEX Volume',
	'Options Notional Volume': 'DEX Volume',
	'Perp Aggregator Volume': 'DEX Volume',
	'Bridge Aggregator Volume': 'DEX Volume',
	'DEX Aggregator Volume': 'DEX Volume',
	Unlocks: 'Unlocks',
	'Active Addresses': 'Active Addresses',
	'New Addresses': 'Active Addresses',
	Transactions: 'Transactions',
	'Gas Used': 'Gas Used',
	'Median APY': 'Median APY',
	'USD Inflows': 'USD Inflows',
	'Total Proposals': 'Total Proposals',
	'Successful Proposals': 'Total Proposals',
	'Max Votes': 'Max Votes',
	Treasury: 'Treasury',
	Tweets: 'Tweets',
	'NFT Volume': 'NFT Volume',
	'Bridge Volume': 'DEX Volume'
}

export const BAR_CHARTS: ProtocolChartsLabels[] = [
	'DEX Volume',
	'Perp Volume',
	'Fees',
	'Revenue',
	'Holders Revenue',
	'Incentives',
	'Active Addresses',
	'New Addresses',
	'Transactions',
	'Gas Used',
	'USD Inflows',
	'Total Proposals',
	'Successful Proposals',
	'Max Votes',
	'Bridge Deposits',
	'Bridge Withdrawals',
	'Token Volume',
	'Tweets',
	'NFT Volume',
	'DEX Aggregator Volume',
	'Options Premium Volume',
	'Options Notional Volume',
	'Perp Aggregator Volume',
	'Bridge Aggregator Volume',
	'Bridge Volume'
]
