import { memo, type SVGProps } from 'react'

type Name =
	| 'arrow-up-right'
	| 'download-cloud'
	| 'chevron-up'
	| 'chevron-down'
	| 'chevron-left'
	| 'chevron-right'
	| 'chevrons-up'
	| 'external-link'
	| 'clock'
	| 'folder-plus'
	| 'trash-2'
	| 'github'
	| 'copy'
	| 'search'
	| 'arrow-left'
	| 'arrow-right'
	| 'flag'
	| 'check-circle'
	| 'help-circle'
	| 'alert-triangle'
	| 'x'
	| 'bookmark'
	| 'settings'
	| 'bar-chart-2'
	| 'activity'
	| 'trending-up'
	| 'users'
	| 'plus'
	| 'repeat'
	| 'link'
	| 'map'
	| 'percent'
	| 'sun'
	| 'moon'
	| 'mail'
	| 'calendar'
	| 'menu'
	| 'code'
	| 'align-left'
	| 'bar-chart'
	| 'eye'
	| 'file-plus'
	| 'file-text'
	| 'layers'
	| 'pie-chart'
	| 'trending-up'
	| 'dollar-sign'
	| 'check'
	| 'card'
	| 'circle-help'
	| 'wallet'
	| 'plug'
	| 'credit-card'
	| 'star'
	| 'ethereum'
	| 'download-paper'
	| 'arrow-up-right-2'
	| 'key'
	| 'linear-unlock'
	| 'cliff-unlock'
	| 'calendar-plus'
	| 'pencil'
	| 'sparkles'
	| 'chat'
	| 'earth'
	| 'twitter'
	| 'file-text'
	| 'flame'
	| 'house'
	| 'pencil-ruler'
	| 'blocks'
	| 'banknote'
	| 'pin'

export interface IIcon extends SVGProps<SVGSVGElement> {
	name: Name
}
export const Icon = memo(function Icon({ name, ...props }: IIcon) {
	return (
		<svg {...props}>
			<use href={`/icons/v9.svg#${name}`} />
		</svg>
	)
})
