export const TOOL_LABELS: Record<string, string> = {
	execute_sql: 'Querying database',
	resolve_entity: 'Resolving entity',
	load_skill: 'Loading knowledge',
	generate_chart: 'Generating visualization',
	generate_image: 'Generating image',
	web_search: 'Searching the web',
	x_search: 'Searching X/Twitter',
	spawn_agent: 'Spawning parallel agents',
	export_csv: 'Exporting CSV',
	export_markdown: 'Exporting Markdown',
	create_alert: 'Creating alert',
	valyu_search: 'Searching financial data',
	execute_code: 'Running code',
	read_url: 'Reading URL',
	get_polymarket_data: 'Fetching prediction markets',
	get_wallet_data: 'Fetching wallet data',
	get_token_data: 'Fetching token data',
	get_tx_data: 'Fetching transaction data',
	get_kg_enrichment: 'Enriching knowledge graph',
	get_feed_enrichment: 'Enriching feed data',
	get_docs: 'Reading documentation',
	read_session_artifacts: 'Reading session artifacts',
	reattach_artifacts: 'Reattaching artifacts',
	list_alerts: 'Listing alerts',
	manage_alert: 'Managing alert',
	search_adapters: 'Searching adapters',
	search_dune: 'Searching Dune',
	get_adapter_code: 'Reading adapter code',
	query_logs: 'Querying logs',
	call_contract: 'Calling contract',
	get_contract: 'Fetching contract',
	etherscan_contract_creation: 'Fetching contract deployment',
	etherscan_address_txs: 'Fetching address transactions',
	etherscan_tx_status: 'Checking transaction status',
	etherscan_gas_oracle: 'Fetching gas prices',
	etherscan_block_info: 'Fetching block info',
	etherscan_l2_bridge_txs: 'Fetching L2 bridge transactions',
	get_monte_carlo_forecast: 'Running Monte Carlo forecast',
	get_tsmom: 'Computing momentum signal',
	get_governance_data: 'Fetching governance data',
	memory: 'Updating memory',
	skill_manage: 'Managing skill',
	skills_list: 'Listing skills',
	skill_view: 'Reading skill',
	todo: 'Updating task list',
	manage_user_memory: 'Updating memory',
	flag_capability_gap: 'Flagging capability gap',
	x_advanced_search: 'Searching X/Twitter',
	x_get_user: 'Fetching X user profile',
	x_get_user_by_id: 'Fetching X user profile',
	x_get_users: 'Fetching X users',
	x_get_tweets: 'Fetching tweets',
	x_get_tweet: 'Fetching tweet',
	x_get_user_tweets: 'Fetching user tweets',
	x_get_mentions: 'Fetching mentions',
	x_get_thread: 'Fetching thread',
	x_search_users: 'Searching X users',
	x_get_followers: 'Fetching X followers',
	x_get_following: 'Fetching X following',
	x_get_quote_tweets: 'Fetching quote tweets',
	x_get_replies: 'Fetching replies',
	x_get_retweeted_by: 'Fetching retweets',
	x_get_community: 'Fetching X community',
	x_get_community_members: 'Fetching community members',
	x_get_community_posts: 'Fetching community posts',
	query_allium: 'Querying onchain data',
	query_dune: 'Querying Dune',
	x_semantic_search: 'Searching X/Twitter',
	apollo_org_search: 'Searching organizations',
	apollo_people_search: 'Searching people',
	apollo_people_enrich: 'Enriching people data',
	apollo_org_enrich: 'Enriching org data',
	clado_linkedin_scrape: 'Scraping LinkedIn profile',
	clado_contacts_enrich: 'Enriching contact data',
	feed_enrichment: 'Enriching feed data',
	generate_dashboard: 'Generating dashboard',
	dashboard_generation_history: 'Loading dashboard history',
	load_dashboard: 'Loading dashboard',
	validate_dashboard_entities: 'Validating dashboard entities',
	list_dashboards: 'Listing dashboards',
	fetch_ohlcv: 'Fetching price data',
	fetch_exchange_data: 'Fetching exchange data',
	get_balance_history: 'Fetching balance history',
	read_result: 'Reading result',
	list_results: 'Listing results',
	x_get_article: 'Reading X article',
	nansen_smart_money_holdings: 'Fetching smart money holdings',
	nansen_smart_money_trades: 'Fetching smart money trades',
	nansen_smart_money_netflow: 'Fetching smart money netflow',
	nansen_token_screener: 'Screening tokens',
	nansen_token_holders: 'Fetching token holders',
	nansen_who_bought_sold: 'Fetching buy/sell data',
	nansen_flow_intelligence: 'Fetching flow intelligence',
	nansen_token_trades: 'Fetching token trades',
	nansen_token_flows: 'Fetching token flows',
	nansen_pnl_leaderboard: 'Fetching PnL leaderboard',
	nansen_pm_event_screener: 'Screening prediction events',
	nansen_pm_market_screener: 'Screening prediction markets',
	nansen_pm_top_holders: 'Fetching top holders',
	nansen_pm_trades: 'Fetching market trades',
	nansen_pm_pnl: 'Fetching market PnL',
	nansen_pm_ohlcv: 'Fetching market OHLCV',
	ls: 'Listing workspace files',
	cat: 'Reading workspace file',
	grep: 'Searching workspace files',
	search_messages: 'Searching messages'
}

export const getToolLabel = (name: string): string =>
	TOOL_LABELS[name] ??
	name
		.split('_')
		.map((word) => (word ? word[0].toUpperCase() + word.slice(1) : word))
		.join(' ')

export const TOOL_ICONS: Record<string, { icon: string; color: string }> = {
	execute_sql: { icon: 'layers', color: '#6366f1' },
	resolve_entity: { icon: 'search', color: '#a78bfa' },
	load_skill: { icon: 'graduation-cap', color: '#34d399' },
	generate_chart: { icon: 'bar-chart-2', color: '#f59e0b' },
	generate_image: { icon: 'image-plus', color: '#2172E5' },
	web_search: { icon: 'earth', color: '#22d3ee' },
	x_search: { icon: 'twitter', color: '#94a3b8' },
	spawn_agent: { icon: 'users', color: '#f472b6' },
	export_csv: { icon: 'sheets', color: '#4ade80' },
	export_markdown: { icon: 'file-text', color: '#60a5fa' },
	create_alert: { icon: 'sparkles', color: '#fbbf24' },
	valyu_search: { icon: 'search', color: '#10b981' },
	execute_code: { icon: 'code', color: '#8b5cf6' },
	read_url: { icon: 'earth', color: '#06b6d4' },
	get_polymarket_data: { icon: 'activity', color: '#ec4899' },
	get_wallet_data: { icon: 'wallet', color: '#f97316' },
	get_token_data: { icon: 'dollar-sign', color: '#eab308' },
	get_tx_data: { icon: 'repeat', color: '#14b8a6' },
	get_kg_enrichment: { icon: 'layers', color: '#6366f1' },
	get_feed_enrichment: { icon: 'layers', color: '#8b5cf6' },
	get_docs: { icon: 'file-text', color: '#22d3ee' },
	read_session_artifacts: { icon: 'file-text', color: '#94a3b8' },
	reattach_artifacts: { icon: 'file-text', color: '#60a5fa' },
	list_alerts: { icon: 'sparkles', color: '#fbbf24' },
	manage_alert: { icon: 'sparkles', color: '#fbbf24' },
	search_adapters: { icon: 'search', color: '#a78bfa' },
	search_dune: { icon: 'search', color: '#f59e0b' },
	get_adapter_code: { icon: 'code', color: '#a78bfa' },
	query_logs: { icon: 'file-text', color: '#94a3b8' },
	call_contract: { icon: 'plug', color: '#6366f1' },
	get_contract: { icon: 'plug', color: '#6366f1' },
	etherscan_contract_creation: { icon: 'plug', color: '#6366f1' },
	etherscan_address_txs: { icon: 'repeat', color: '#14b8a6' },
	etherscan_tx_status: { icon: 'activity', color: '#14b8a6' },
	etherscan_gas_oracle: { icon: 'activity', color: '#f59e0b' },
	etherscan_block_info: { icon: 'layers', color: '#6366f1' },
	etherscan_l2_bridge_txs: { icon: 'repeat', color: '#14b8a6' },
	get_monte_carlo_forecast: { icon: 'trending-up', color: '#f472b6' },
	get_tsmom: { icon: 'trending-up', color: '#f59e0b' },
	get_governance_data: { icon: 'users', color: '#8b5cf6' },
	memory: { icon: 'bookmark', color: '#34d399' },
	skill_manage: { icon: 'graduation-cap', color: '#34d399' },
	skills_list: { icon: 'graduation-cap', color: '#34d399' },
	skill_view: { icon: 'graduation-cap', color: '#34d399' },
	todo: { icon: 'check-circle', color: '#34d399' },
	manage_user_memory: { icon: 'bookmark', color: '#34d399' },
	flag_capability_gap: { icon: 'flag', color: '#f43f5e' },
	x_advanced_search: { icon: 'twitter', color: '#94a3b8' },
	x_get_user: { icon: 'twitter', color: '#94a3b8' },
	x_get_user_by_id: { icon: 'twitter', color: '#94a3b8' },
	x_get_users: { icon: 'twitter', color: '#94a3b8' },
	x_get_tweets: { icon: 'twitter', color: '#94a3b8' },
	x_get_tweet: { icon: 'twitter', color: '#94a3b8' },
	x_get_user_tweets: { icon: 'twitter', color: '#94a3b8' },
	x_get_mentions: { icon: 'twitter', color: '#94a3b8' },
	x_get_thread: { icon: 'twitter', color: '#94a3b8' },
	x_search_users: { icon: 'twitter', color: '#94a3b8' },
	x_get_followers: { icon: 'twitter', color: '#94a3b8' },
	x_get_following: { icon: 'twitter', color: '#94a3b8' },
	x_get_quote_tweets: { icon: 'twitter', color: '#94a3b8' },
	x_get_replies: { icon: 'twitter', color: '#94a3b8' },
	x_get_retweeted_by: { icon: 'twitter', color: '#94a3b8' },
	x_get_community: { icon: 'twitter', color: '#94a3b8' },
	x_get_community_members: { icon: 'twitter', color: '#94a3b8' },
	x_get_community_posts: { icon: 'twitter', color: '#94a3b8' },
	query_allium: { icon: 'layers', color: '#6366f1' },
	query_dune: { icon: 'layers', color: '#f59e0b' },
	x_semantic_search: { icon: 'twitter', color: '#94a3b8' },
	apollo_org_search: { icon: 'search', color: '#8b5cf6' },
	apollo_people_search: { icon: 'users', color: '#8b5cf6' },
	apollo_people_enrich: { icon: 'users', color: '#a78bfa' },
	apollo_org_enrich: { icon: 'search', color: '#a78bfa' },
	clado_linkedin_scrape: { icon: 'users', color: '#0077b5' },
	clado_contacts_enrich: { icon: 'users', color: '#0077b5' },
	feed_enrichment: { icon: 'layers', color: '#8b5cf6' },
	generate_dashboard: { icon: 'layout-grid', color: '#2563eb' },
	dashboard_generation_history: { icon: 'layout-grid', color: '#6366f1' },
	load_dashboard: { icon: 'layout-grid', color: '#6366f1' },
	validate_dashboard_entities: { icon: 'layout-grid', color: '#8b5cf6' },
	list_dashboards: { icon: 'layout-grid', color: '#6366f1' },
	fetch_ohlcv: { icon: 'bar-chart-2', color: '#f59e0b' },
	fetch_exchange_data: { icon: 'bar-chart-2', color: '#f97316' },
	get_balance_history: { icon: 'wallet', color: '#f97316' },
	read_result: { icon: 'file-text', color: '#94a3b8' },
	list_results: { icon: 'file-text', color: '#94a3b8' },
	x_get_article: { icon: 'twitter', color: '#94a3b8' },
	nansen_smart_money_holdings: { icon: 'trending-up', color: '#2563eb' },
	nansen_smart_money_trades: { icon: 'trending-up', color: '#2563eb' },
	nansen_smart_money_netflow: { icon: 'trending-up', color: '#2563eb' },
	nansen_token_screener: { icon: 'search', color: '#2563eb' },
	nansen_token_holders: { icon: 'users', color: '#2563eb' },
	nansen_who_bought_sold: { icon: 'repeat', color: '#2563eb' },
	nansen_flow_intelligence: { icon: 'activity', color: '#2563eb' },
	nansen_token_trades: { icon: 'repeat', color: '#2563eb' },
	nansen_token_flows: { icon: 'activity', color: '#2563eb' },
	nansen_pnl_leaderboard: { icon: 'trending-up', color: '#2563eb' },
	nansen_pm_event_screener: { icon: 'activity', color: '#ec4899' },
	nansen_pm_market_screener: { icon: 'search', color: '#ec4899' },
	nansen_pm_top_holders: { icon: 'users', color: '#ec4899' },
	nansen_pm_trades: { icon: 'repeat', color: '#ec4899' },
	nansen_pm_pnl: { icon: 'trending-up', color: '#ec4899' },
	nansen_pm_ohlcv: { icon: 'bar-chart-2', color: '#ec4899' },
	ls: { icon: 'file-text', color: '#94a3b8' },
	cat: { icon: 'file-text', color: '#94a3b8' },
	grep: { icon: 'search', color: '#94a3b8' },
	search_messages: { icon: 'search', color: '#94a3b8' }
}
