/** Protocols excluded from the airdrops page. */
export const AIRDROP_EXCLUDE = new Set([
	'DeerFi',
	'FireDAO',
	'Robo-Advisor for Yield',
	'SenpaiSwap',
	'Zunami Protocol',
	'NowSwap',
	'NeoBurger',
	'MochiFi',
	'StakeHound',
	'Lightning Network',
	'Secret Bridge',
	'Karura Swap',
	'Karura Liquid-Staking',
	'Karura Dollar (kUSD)',
	'Tezos Liquidity Baking',
	'Notional',
	'Tinlake',
	'Kuu Finance',
	'COTI Treasury',
	'Terra Bridge',
	'Parallel Liquid Crowdloan',
	'Parallel Liquid Staking',
	'Parallel Lending',
	'Parallel AMM',
	'Parallel DAOfi',
	'Algofi Lend',
	'Algofi Swap',
	'BNBMiner Finance',
	'Gnosis Protocol v1',
	'Multi-Chain Miner',
	'Swap Cat',
	'FLRLoans',
	'Pando Leaf',
	'Pando Rings',
	'4Swap',
	'REX Staking',
	'Sapphire Mine',
	'MM Stableswap',
	'MM Stableswap Polygon',
	'Sushi Furo',
	'Sushi Trident',
	'Poly Network',
	'Frax Swap',
	'Kava Mint',
	'Quarry',
	'Canto Dex',
	'Katana DEX',
	'Canto Lending',
	'OKCSwap',
	'Fraxlend',
	'Tesseract',
	'Spartacus Exchange',
	'NerveSwap',
	'NULS POCM',
	'NerveBridge',
	'Djed Stablecoin',
	'USK',
	'Bow',
	'FIN',
	'Black Whale',
	'CALC',
	'BAO Ballast',
	'BAO Baskets',
	'BAO Markets',
	'BAO Swap',
	'RealT RMM Marketplace',
	'Bifrost Liquid Crowdloan',
	'Kava Boost',
	'Kava Earn',
	'Kava Liquid',
	'Algo Liquid Governance',
	'WanLend',
	'sKCS',
	'Lachain Yield Market',
	'Ladex Exchange',
	'Oswap',
	'BabelFish',
	'ThetaSwap',
	'MooniSwap',
	'Talent Protocol',
	'RealT Tokens',
	'TTswap',
	'Ethereum Foundation',
	'THORWallet DEX',
	'Nouns',
	'Libre Swap',
	'Omax Swap',
	'Zeniq Swap',
	'LaDAO Xocolatl',
	'Meter Passport',
	'Metavault Binary Options',
	'Wan Bridge',
	'DarkAuto',
	'Crescent Dex',
	'Lago Bridge',
	'Ostable',
	'Oswap AMM',
	'WBTC',
	'Binance staked ETH',
	'Coinbase Wrapped Staked ETH',
	'hBTC',
	'Mantle Staked ETH',
	'Jupiter Perpetual Exchange',
	'Binance Staked SOL',
	'Binance Bitcoin'
])
