/**
 * Editorial report template — renders a LlamaAI research-mode message as a
 * standalone HTML artifact. Pure function: no DOM, no fetching, no side effects.
 *
 * Always renders with DefiLlama branding in PR1; user-configurable brand kit
 * (logo, primary color, title/footer overrides) is a separate feature.
 */

import rehypeRaw from 'rehype-raw'
import rehypeSanitize from 'rehype-sanitize'
import rehypeStringify from 'rehype-stringify'
import remarkGfm from 'remark-gfm'
import remarkParse from 'remark-parse'
import remarkRehype from 'remark-rehype'
import { unified } from 'unified'
import { SANITIZE_SCHEMA } from '~/containers/LlamaAI/components/markdown/sanitizeConfig'
import { parseMessageToRenderModel } from '~/containers/LlamaAI/renderModel'
import type { Message } from '~/containers/LlamaAI/types'
import {
	escapeBareOrderedListMarkers,
	normalizeSourceUrl,
	processCitationMarkers
} from '~/containers/LlamaAI/utils/markdownHelpers'
import { escapeHtml } from '~/containers/LlamaAI/utils/textUtils'

export interface ChartImage {
	dataUrl: string
	title?: string
}

interface EditorialReportInput {
	message: Message
	/** Map of chart artifact id → exported chart (PNG + title). Generated by exportArtifact orchestrator. */
	chartImages: Map<string, ChartImage>
	/** Data URL for the DefiLlama wordmark used in "Powered by" line. Inlined for offline portability. */
	defillamaWordmarkDataUrl?: string
	/** Timestamp shown in header + footer. Defaults to now. */
	generatedAt?: Date
}

const REPORT_TITLE = 'DefiLlama Research Report'
// DefiLlama brand blue. Same value as the [#2172e5] literals across the SPA;
// duplicated here because the exported artifact has no access to app CSS tokens.
const PRIMARY_COLOR = '#2172E5'

// The export pipeline lets server-emitted markdown through with `allowDangerousHtml`
// (so processCitationMarkers's <citation-badge> tags survive), then runs the same
// rehype-sanitize schema that the in-chat ChatMarkdownRenderer uses. Without
// sanitization, an injected `<script>` in the source message would land in the
// exported artifact and execute in the recipient's browser.
const markdownProcessor = unified()
	.use(remarkParse)
	.use(remarkGfm)
	.use(remarkRehype, { allowDangerousHtml: true })
	.use(rehypeRaw)
	.use(rehypeSanitize, SANITIZE_SCHEMA)
	.use(rehypeStringify)

async function renderMarkdownToHtml(content: string, citations?: string[]): Promise<string> {
	const processed = escapeBareOrderedListMarkers(processCitationMarkers(content, citations))
	const file = await markdownProcessor.process(processed)
	return String(file)
}

function renderSourcesList(citations: string[]): string {
	const items = citations
		.map((rawUrl, idx) => {
			const url = normalizeSourceUrl(rawUrl)
			const safeUrl = escapeHtml(url)
			return `<li><a href="${safeUrl}" target="_blank" rel="noopener noreferrer"><span class="cite-num">${idx + 1}</span><span class="cite-url">${safeUrl}</span></a></li>`
		})
		.join('')
	return `<section class="sources"><h2>Sources</h2><ol class="sources-list">${items}</ol></section>`
}

function formatDate(date: Date): string {
	return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function renderHeader(dateStr: string, wordmarkDataUrl: string | undefined): string {
	const headerLogoHtml = wordmarkDataUrl
		? `<img class="user-logo defillama-fallback" src="${escapeHtml(wordmarkDataUrl)}" alt="DefiLlama" />`
		: ''
	const poweredBy = wordmarkDataUrl
		? `<div class="powered-by"><span>Powered by</span><img src="${escapeHtml(wordmarkDataUrl)}" alt="DefiLlama" /></div>`
		: `<div class="powered-by"><span>Powered by DefiLlama</span></div>`
	return `<header class="report-header">
		<div class="header-row">
			<div class="header-left">${headerLogoHtml}</div>
			<div class="header-right">${poweredBy}<div class="report-date">${escapeHtml(dateStr)}</div></div>
		</div>
		<h1 class="report-title">${escapeHtml(REPORT_TITLE)}</h1>
	</header>`
}

function renderFooter(dateStr: string): string {
	return `<footer class="report-footer">
		<div class="footer-disclaimer">Data as of ${escapeHtml(dateStr)}. Source: DefiLlama and cited web sources. Web-sourced context is unverified by DefiLlama. NFA, DYOR.</div>
		<div class="defillama-attribution">Data via <a href="https://defillama.com" target="_blank" rel="noopener noreferrer">defillama.com</a></div>
	</footer>`
}

function buildStyles(): string {
	const r = parseInt(PRIMARY_COLOR.slice(1, 3), 16)
	const g = parseInt(PRIMARY_COLOR.slice(3, 5), 16)
	const b = parseInt(PRIMARY_COLOR.slice(5, 7), 16)
	const accentRgba = (alpha: number) => `rgba(${r}, ${g}, ${b}, ${alpha})`
	return `
		:root {
			--brand-primary: ${PRIMARY_COLOR};
			--brand-primary-faint: ${accentRgba(0.08)};
			--brand-primary-border: ${accentRgba(0.2)};
			--text-primary: #111;
			--text-secondary: #555;
			--text-muted: #888;
			--bg: #fff;
			--bg-alt: #f7f7f7;
			--border: #e6e6e6;
			--border-strong: #d0d0d0;
		}
		* { box-sizing: border-box; }
		body {
			margin: 0;
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
			font-size: 15px;
			line-height: 1.6;
			color: var(--text-primary);
			background: var(--bg);
		}
		.report {
			max-width: 920px;
			margin: 0 auto;
			padding: 48px 32px 64px;
		}
		.report-header {
			border-bottom: 3px solid var(--brand-primary);
			padding-bottom: 24px;
			margin-bottom: 32px;
		}
		.header-row {
			display: flex;
			justify-content: space-between;
			align-items: center;
			margin-bottom: 24px;
			gap: 16px;
		}
		.header-left { display: flex; align-items: center; }
		.header-right { display: flex; flex-direction: column; align-items: flex-end; gap: 4px; text-align: right; }
		.user-logo { max-height: 48px; max-width: 200px; width: auto; height: auto; }
		.user-logo.defillama-fallback { max-height: 36px; }
		.powered-by { display: flex; align-items: center; gap: 6px; font-size: 12px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.04em; }
		.powered-by img { height: 16px; width: auto; }
		.report-date { font-size: 13px; color: var(--text-muted); }
		.report-title { font-size: 32px; font-weight: 700; margin: 0; line-height: 1.2; color: var(--text-primary); }
		.report-body { font-size: 15px; }
		.report-body h1, .report-body h2, .report-body h3 { font-weight: 600; line-height: 1.3; color: var(--text-primary); }
		.report-body h1 { font-size: 26px; margin: 40px 0 16px; }
		.report-body h2 { font-size: 22px; margin: 36px 0 14px; padding-top: 16px; border-top: 1px solid var(--border); }
		.report-body h2:first-of-type { border-top: none; padding-top: 0; }
		.report-body h3 { font-size: 17px; margin: 24px 0 10px; }
		.report-body p { margin: 0 0 14px; }
		.report-body ul, .report-body ol { margin: 0 0 14px; padding-left: 24px; }
		.report-body li { margin-bottom: 6px; }
		.report-body a { color: var(--brand-primary); text-decoration: none; }
		.report-body a:hover { text-decoration: underline; }
		.report-body strong { font-weight: 600; }
		.report-body em { font-style: italic; }
		.report-body code { background: var(--bg-alt); padding: 2px 6px; border-radius: 3px; font-size: 0.9em; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
		.report-body pre { background: var(--bg-alt); padding: 12px 16px; border-radius: 6px; overflow-x: auto; font-size: 13px; }
		.report-body table {
			width: 100%;
			border-collapse: collapse;
			margin: 16px 0 24px;
			font-size: 14px;
		}
		.report-body th, .report-body td {
			border: 1px solid var(--border);
			padding: 8px 12px;
			text-align: left;
			vertical-align: top;
		}
		.report-body th {
			background: var(--bg-alt);
			font-weight: 600;
		}
		.report-body tr:nth-child(even) td { background: #fafafa; }
		.report-body blockquote {
			margin: 16px 0;
			padding: 8px 16px;
			border-left: 3px solid var(--brand-primary);
			background: var(--brand-primary-faint);
			color: var(--text-secondary);
		}
		.chart { margin: 24px 0; text-align: center; page-break-inside: avoid; }
		.chart img { max-width: 100%; height: auto; border-radius: 6px; }
		.chart figcaption { margin-top: 8px; font-size: 13px; color: var(--text-secondary); }
		.sources { margin-top: 48px; padding-top: 24px; border-top: 1px solid var(--border); }
		.sources h2 { font-size: 18px; margin: 0 0 16px; padding-top: 0; border-top: none; }
		.sources-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 8px; }
		.sources-list li { margin: 0; }
		.sources-list a { display: flex; gap: 10px; padding: 8px 12px; border: 1px solid var(--border); border-radius: 6px; color: var(--text-primary); text-decoration: none; }
		.sources-list a:hover { border-color: var(--brand-primary); background: var(--brand-primary-faint); }
		.cite-num { flex-shrink: 0; background: var(--brand-primary-faint); color: var(--brand-primary); padding: 0 6px; border-radius: 3px; font-size: 12px; font-weight: 500; }
		.cite-url { color: var(--text-secondary); font-size: 13px; word-break: break-all; }
		citation-badge {
			display: inline-flex;
			align-items: center;
			justify-content: center;
			min-width: 18px;
			height: 18px;
			padding: 0 4px;
			margin: 0 1px;
			border: 1px solid var(--brand-primary-border);
			background: var(--brand-primary-faint);
			color: var(--brand-primary);
			font-size: 11px;
			font-weight: 500;
			border-radius: 4px;
			line-height: 1;
			text-decoration: none;
		}
		citation-badge a, a citation-badge { color: inherit; text-decoration: none; }
		.report-footer {
			margin-top: 64px;
			padding-top: 24px;
			border-top: 1px solid var(--border);
			font-size: 12px;
			color: var(--text-muted);
			line-height: 1.5;
		}
		.footer-disclaimer { margin-bottom: 8px; }
		.defillama-attribution a { color: var(--brand-primary); text-decoration: none; }
		.defillama-attribution a:hover { text-decoration: underline; }
		@media print {
			.report { padding: 24px; max-width: none; }
			.chart { page-break-inside: avoid; }
			.report-body h2 { page-break-after: avoid; }
			body { font-size: 12pt; }
		}
	`
		.replace(/\s*\n\s*/g, ' ')
		.trim()
}

// Styles depend only on the fixed DefiLlama brand color in PR1, so build them
// once at module load instead of on every export.
const STYLES = buildStyles()

/**
 * Render a LlamaAI message (typically a research-mode response) as a complete
 * standalone HTML document. Returns the HTML as a string.
 */
export async function renderEditorialReport(input: EditorialReportInput): Promise<string> {
	const generatedAt = input.generatedAt ?? new Date()
	const dateStr = formatDate(generatedAt)

	const { blocks } = parseMessageToRenderModel(input.message)

	const bodyParts: string[] = []
	const sourcesParts: string[] = []
	for (const block of blocks) {
		if (block.type === 'markdown') {
			bodyParts.push(await renderMarkdownToHtml(block.content, block.citations))
		} else if (block.type === 'chart') {
			const chart = input.chartImages.get(block.artifactId)
			if (chart) {
				const altText = escapeHtml(chart.title ?? 'Chart')
				const caption = chart.title ? `<figcaption>${escapeHtml(chart.title)}</figcaption>` : ''
				bodyParts.push(
					`<figure class="chart"><img src="${chart.dataUrl}" alt="${altText}" loading="lazy" />${caption}</figure>`
				)
			}
		} else if (block.type === 'sources') {
			sourcesParts.push(renderSourcesList(block.citations))
		}
		// csv / md / alert / dashboard / image / action-group blocks are deliberately
		// excluded from the printed artifact. CSVs and markdown files are downloadable
		// adjacent artifacts; dashboards/alerts/actions are interactive surfaces with
		// no useful static equivalent. Future iterations may surface CSV/MD as a
		// "Related downloads" appendix.
	}

	const header = renderHeader(dateStr, input.defillamaWordmarkDataUrl)

	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(REPORT_TITLE)}</title>
<style>${STYLES}</style>
</head>
<body>
<article class="report">
${header}
<div class="report-body">
${bodyParts.join('\n')}
</div>
${sourcesParts.join('\n')}
${renderFooter(dateStr)}
</article>
</body>
</html>`
}
